#!/bin/bash

# JankyBorders configuration
# Shows a visible border around the active window

options=(
    style=round
    width=6.0
    hidpi=on
    active_color=0xff87c3ed
    # inactive_color=0xff494d64
)

borders "${options[@]}"
