#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_placement second_child

# ----------
# padding
# ----------
yabai -m config external_bar all:24:0 # 32 = heigh of sketchybar
yabai -m config bottom_padding_overlap true # take up space of hidden dock
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 5
yabai -m config window_padding_top 10
yabai -m config window_padding_bottom 10
yabai -m config window_padding_left 10
yabai -m config window_padding_right 10

# ----------
# mouse
# ----------
yabai -m config mouse_follows_focus 1
yabai -m config mouse_modifier alt
# left click+drag
yabai -m config mouse_action1 move
# right click+d
yabai -m config mouse_action2 resize
yabai -m config focus_follows_mouse 1
yabai -m mouse_drop_action swap

# ----------
# exclude apps from being resized
# ----------
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Activity Monitor|Karabiner-Elements)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

echo "yabai config. loaded."

