#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_placement second_child

# ----------
# padding
# ----------
yabai -m config bottom_padding_overlap true # take up space of hidden dock
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 5
yabai -m config window_padding_top 10
yabai -m config window_padding_bottom 10
yabai -m config window_padding_left 10
yabai -m config window_padding_right 10

# ----------
# mouse
# ----------
yabai -m config mouse_follows_focus 1
yabai -m config mouse_modifier alt
# left click+drag
yabai -m config mouse_action1 move
# right click+d
yabai -m config mouse_action2 resize
yabai -m config focus_follows_mouse 1
yabai -m mouse_drop_action swap


# ----------
# disable specfiic apps
# ----------
yabai -m rule --add="^System Settings$" manage=off
yabai -m rule --add="^Calculator$" manage=off
yabai -m rule --add="^Karabiner-Elements$" manage=off
